### -------------------------------- Config -------------------------------- ###
app_name="StockWidget" # used as name for reg variable for auto startup
# stock_symbol = "mu"
legend_color = 'white'
chart_area_color_positive = 'green' # used with matplotlib (outdated)
chart_area_color_negative = '#a60c0c' # used with matplotlib (outdated)
chart_area_color_positive_trans = (0, 255, 0, 20) # used with pyqtgraph
chart_area_color_negative_trans = (255, 0, 0, 20) # used with pyqtgraph
chart_line_color_positive = '#4ece6f'
chart_line_color_negative = '#ff2626'
area_chart = True
monday_lines = True
monday_lines_color = 'white'
monday_lines_style = 'solid' # https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
monday_lines_transparency = 0.5
monday_lines_width = 1
horizontal_lines = True
horizontal_lines_color = 'white'
horizontal_lines_style = (0, (5, 10)) # https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
horizontal_lines_transparency = 0.5
horizontal_lines_width = 0.5
# padding_multiplier = 0.4 # deprecated
# y_label_every_x_datapoints = 100 # deprecated
title_font_size = 20
update_font_size = 8
crosshair = True
display_first_date_as_tick = True
drag_window = False
display_refresh_time = True
retries = 5
refresh_interval = 3600 # seconds
# refresh_interval = 20 # seconds
window_margins = [10, 10, 10, 10]
log_to_file = False
debug = False # set to False for pyinstaller
# debug = True # set to False for pyinstaller
### ------------------------------------------------------------------------ ###